#extracts phonemes from minimal_pairs.txt which is generated by minimal_pairs.py

f = open('files/minimal_pairs.txt', 'r', encoding='utf-8')

phonemes = set()

line = f.readline()
while line:
    line = line.strip()
    if line != '':
        line = line.split()
        phonemes.add(line[2])
        phonemes.add(line[3])
    line = f.readline()

print(phonemes)

#for later use in the program that finds allophones
import pickle
wf = open('files/phonemes.dat', 'wb')
pickle.dump(phonemes, wf)

f.close()
wf.close()