#extracts phonemes from minimal_pairs.txt which is generated by minimal_pairs.py

import sys
import io

# Set stdout to UTF-8 encoding
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
# makes it possible to redirect stdout to file using > operator in windows, as default encodign doesn't support all utf-8 characters

f = open('files/minimal_pairs.txt', 'r', encoding='utf-8')

phonemes = set()

line = f.readline()
while line:
    line = line.strip()
    if line != '':
        line = line.split()
        phonemes.add(line[2])
        phonemes.add(line[3])
    line = f.readline()

print(phonemes)

#for later use in the program that finds allophones
import pickle
wf = open('files/phonemes.dat', 'wb')
pickle.dump(phonemes, wf)

f.close()
wf.close()